# Generated by Django 5.2.7 on 2025-10-15 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_logininfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='newapp.logininfo')),
            ],
        ),
    ]
